ERROR - 2023-03-26 05:44:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:44:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:44:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:44:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:44:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:44:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:09 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:09 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 05:47:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 05:47:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:25:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:25:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:25:55 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:25:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:51:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:51:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:53:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:53:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:53:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:53:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:54:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:54:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:54:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:54:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:54:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:54:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:54:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:54:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:54:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:54:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:54:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:54:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:54:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'checkthe_igni598'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/checkthe/public_html/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#4 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#5 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#7 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#8 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#9 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#10 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#11 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-26 17:54:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Directory.php(15): view()
 8 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:56:19 --> mysqli_sql_exception: Table 'checkthe_main.a3restaraunts' doesn't exist in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:292
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(292): mysqli->query()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-03-26 17:56:19 --> Table 'checkthe_main.a3restaraunts' doesn't exist
in SYSTEMPATH/Database/MySQLi/Connection.php on line 292.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(292): mysqli->query()
 2 SYSTEMPATH/Database/BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute()
 3 SYSTEMPATH/Database/BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery()
 4 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 5 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 7 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 9 APPPATH/Controllers/Directory.php(15): view()
10 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
11 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
12 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
13 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-26 17:56:19 --> mysqli_sql_exception: Table 'checkthe_main.a3restaraunts' doesn't exist in /home/checkthe/public_html/system/Database/MySQLi/Connection.php:292
Stack trace:
#0 /home/checkthe/public_html/system/Database/MySQLi/Connection.php(292): mysqli->query()
#1 /home/checkthe/public_html/system/Database/BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /home/checkthe/public_html/system/Database/BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /home/checkthe/public_html/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /home/checkthe/public_html/app/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
#5 /home/checkthe/public_html/system/View/View.php(213): include('/home/checkthe/...')
#6 /home/checkthe/public_html/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /home/checkthe/public_html/system/Common.php(1135): CodeIgniter\View\View->render()
#8 /home/checkthe/public_html/app/Controllers/Directory.php(15): view()
#9 /home/checkthe/public_html/system/CodeIgniter.php(925): App\Controllers\Directory->index()
#10 /home/checkthe/public_html/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
#11 /home/checkthe/public_html/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
#12 /home/checkthe/public_html/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-03-26 17:56:19 --> Table 'checkthe_main.a3restaraunts' doesn't exist
in SYSTEMPATH/Database/MySQLi/Connection.php on line 292.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(292): mysqli->query()
 2 SYSTEMPATH/Database/BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute()
 3 SYSTEMPATH/Database/BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery()
 4 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 5 APPPATH/Views/directory/index.php(25): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 7 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 9 APPPATH/Controllers/Directory.php(15): view()
10 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
11 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
12 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
13 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-26 17:56:30 --> urldecode(): Passing null to parameter #1 ($string) of type string is deprecated
in APPPATH/Views/directory/index.php on line 60.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/Views/directory/index.php(60): urldecode()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/directory/index.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Directory.php(15): view()
 7 SYSTEMPATH/CodeIgniter.php(925): App\Controllers\Directory->index()
 8 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
